### ISSUE TITLE
pickle on windows and build/install extension from source

### ISSUE THREAD

**Issue by clickalicious** [FriendsOfPHP/pickle#104]
@weltling i tried a lot to get pickle running ... followed your recommendations here: https://github.com/clickalicious/php_zopfli/pull/5#issuecomment-76916031

I springcleaned my development system. Removed D:\php-sdk and all content. Created a fresh new clean C:\php-sdk based on source of PHP 5.5.22. Added binaries + build dependencies (following my own guide: http://www.phpfluesterer.de/software-architecture/compile-php-and-or-an-extension-under-win-x86/). Checked that i can compile my own extension like described in my guide (link above). Everything works fine as long as i compile my extension following my guide.

Now we come to pickle. The process confuses me a bit ... I assume its just caused by path juggling... 

I followed all steps you described above:
 - used C:\php-sdk
 - added the correct development package
 - added the (C:\php-sdk\phpdev\vc11\x86\php-source-directory\win32\build\phpize.bat) to %path% (Is this the correct one? If i call it manually from its folder it says "...phpize.js not found"
 - I use the VS2012 x86 Native Shell (based on cmd - shipped with MS VS 20XX)

And now the magic i really don't understand ...

Opening shell, navigate to "c:\php-sdk\phpdev\vc11\x86\php-source-directory" and calling "c:\php-sdk\phpdev\vc11\x86\php-source-directory>php C:\Development\web\pickle\bin\pickle info C:\php-sdk\phpdev\vc11\x86\pecl\zopfli-0.2.0"

pickle shows me the correct information about zopfli without any errors. This let me assume that pickle in general works fine, that pickle can handle the paths', that pickle find my extension and is able to read the information ...

At this point i thought - yeah i got it ... but ...

If I keep in directory "c:\php-sdk\phpdev\vc11\x86\php-source-directory" and call "php C:\Development\web\pickle\bin\pickle install C:\php-sdk\phpdev\vc11\x86\pecl\zopfli-0.2.0 --source"

The following error(s) happened: configure failed, see log at C:\Users\BENJAM~1.CAR\AppData\Local\Temp/pickle-zopfli0.2.0.0\config.log
Would you like to read the log?yes

1: phpsdk_setvars
2: set vars succeeded!

1: phpize
2: Eingabefehler: Die Skriptdatei "C:\php-sdk\phpdev\vc11\x86\php-source-directory\win32\build\script\phpize.js" wurde nicht gefunden.
2: Now run 'configure --help'

1: C:\php-sdk\phpdev\vc11\x86\pecl\zopfli-0.2.0/configure --enable-zopfli=shared
  --enable-zopfli
2: Der Befehl "C:\php-sdk\phpdev\vc11\x86\pecl\zopfli-0.2.0/configure" ist entweder falsch geschrieben oder
2: konnte nicht gefunden werden.

The second 2: Translates to: "Input error: The script file: "...phpize.js" could not be found.
The fourth 2: Translates to: The command "...configure" is either wrong or could not be found.

Maybe you see something i did wrong or we talking about a bug. I'm not sure yet.

**Comment by weltling** [comment]
@clickalicious with development package, I meant literally one like here http://windows.php.net/downloads/releases/php-devel-pack-5.5.22-nts-Win32-VC11-x86.zip (choose appropriate variant).

To build just one extension the full PHP source isn't required. An archive like above contains phpize and all the necessary libs, headers and scripts. Of course if there are extra deps, care has to be taken separately. ext/zopfli doesn't have any, so not the case.

So generally getting that dev zipball, exctacting it somewhere and putting it onto the path is what needed. A good idea were probably using standard paths like c:\php\sdk . This is probably the only point where your setup is not correct. Also note that the scripts in the dev package are generated on the PHP build time.

Pickle will use the standard sequence of the commands like phpize/buildconf/configure/nmake. It'll also automatically recognize the configure options in most cases. It'll then install the DLL into c:\php . This shema is actually worky also when running commands manually, so you can play with this for better understanting of what is going on.

Thanks.

**Comment by pierrejoye** [comment]
The detection part of the tools required to build extension without the full php-src tree will be added, to avoid this kind of cryptic errors :)

btw, here are the general instructions, while phpize method is missing: https://wiki.php.net/internals/windows

**Comment by clickalicious** [comment]
OK. @weltling Thanks for the detailed response and the details i didn't knew ... Heard about that for the first time. For a longer time the compile process on windows was somewhat "magic" or "voodoo" like ... :) From that time i have a lot of workarounds - pickle seems helping to get rid of it ...

Sure you mean "c:\php\sdk" not "C:\php-sdk"? Cause this is whats referenced in pickle here: https://github.com/FriendsOfPHP/pickle/blob/master/src/Package/PHP/Command/Build/Windows.php#L14

Successfully build the extension with pickle :) This made my day guys! Thank you!

 - The path where pickle put the extension (dll) is currently not configurable and points to C:\php correct?
 If the question above is answered with yes then pickle should do a check if C:\php exists :) Otherwise it just creates a C:\php (FILE!) with binary in and pickle's cli output let assume that everything went fine. I can create an clean issue with details for that. Maybe i find some time to implement this ...

@pierrejoye Sounds great - today its not longer that complicated to run the build process but it's still damn difficult to get all the information required to do. Thanks for the link (https://wiki.php.net/internals/windows) - the site also contains information i've never seen before - Btw the last 2 links are dead/404 ...

**Comment by pierrejoye** [comment]
Quick note: pickle puts the extension in the directory defined by extension_dir, the one used to run pickle itself, no magic here :)

**Comment by Hywan** [comment]
State of this issue?

**Comment by weltling** [comment]
Yeah, thanks for the ping ... the issue about the prefix was fixed short after the report in march http://git.php.net/?p=php-src.git;a=commitdiff;h=6b643f0741e59fb2473e23c0ead6715b661845b1 , so it's in 5.5+. The main topic is already reported to have been solved, anyway.

Thanks.

**Comment by pierrejoye** [comment]
so it is solved? @weltling ?

If yes, please close this issue :)

**Comment by weltling** [comment]
@pierrejoye yeah, the issue with creating the install dir was fixed in the mentioned commit.
