### ISSUE TITLE
update logo 

### ISSUE THREAD

**Issue by pierrejoye** [FriendsOfPHP/pickle#107]
Update the logo to have the cool new logo we use on pickleweb

**Comment by Hywan** [comment]
I reckon we can close this issue :smile:?

**Comment by pierrejoye** [comment]
Do we use the ascii/ANSI version of the new logo now?

**Comment by Hywan** [comment]
No idea :-).

**Comment by pierrejoye** [comment]
Can be seen using the pickle command line and compared with the new logo.
So no, we do not use the new one in the console tool :)

**Comment by Hywan** [comment]
So…

**Comment by pierrejoye** [comment]
Did you commit the new logo? Or am I missing something? This bug is about
getting the new logo in the pickle tool instead of what we use now :)

On Mon, Jul 6, 2015 at 3:12 PM, Ivan Enderlin <notifications@github.com>
wrote:

> So…
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FriendsOfPHP/pickle/issues/107#issuecomment-118768455>
> .
>



-- 
Pierre

@pierrejoye | http://www.libgd.org

**Comment by Hywan** [comment]
:stuck_out_tongue:
