### ISSUE TITLE
If not engine specified in composer, default to php

### ISSUE THREAD

**Issue by pierrejoye** [FriendsOfPHP/pickle#110]
To support old extension (convert automatically) or extension with a composer.json without the supported engines listed, it should default to PHP

**Comment by pierrejoye** [comment]
Has to be done on convert as well, so the engine will be present in the generated composer.json

**Comment by pierrejoye** [comment]
I think it is fixed now?  @weltling ? :)

**Comment by weltling** [comment]
Nope, it seems not to be fixed. And I somehow haven't check this issue before ( ... While defaulting to PHP can be done, what I see in the composer docs https://getcomposer.org/doc/04-schema.md - there's no exact entry under which we can list the engine, it only allows PHP version.

But also now in particular, as pickle has 5.4 dependency - that's what is held. It might not know the correct PHP paths for other versions but but just use the PHP pickle was invoked with. IMHO it is not critical for the next release anyway - while HHVM is basically supported, PHP is what only really works regarding installation.

Thanks.

**Comment by pierrejoye** [comment]
Not relevant anymore, only PHP is supported.
