### ISSUE TITLE
Package version validation isn't happening extensively

### ISSUE THREAD

**Issue by weltling** [FriendsOfPHP/pickle#111]
Namely, the versions between composer.json and PHP_EXT_VERSION in the php_ext.h need to match. This is for PHP, however the implementation needs to spread over all the engines an appropriate way.

**Comment by pierrejoye** [comment]
Some steps:
* drop version in composer.json
* rmtools should add it
* only PHP_<extname>_VERSION must be used
* Use PHP_<extname>_VERSION to show the command to create the tag & push
* check if the version already exists as tag (remote)

**Comment by weltling** [comment]
rmtools currently parses the pickle output https://github.com/OSTC/web-rmtools/blob/master/client/include/PickleExt.php#L40 , the zip name is then constructed using that data https://github.com/OSTC/web-rmtools/blob/master/client/script/pickle.php#L119 ... probably it would make sense then to concentrate all the check in pickle - easier to catch bugs, other places can just parse it's output and rely on it.

**Comment by weltling** [comment]
Looks like this is fixed through #113 and #114. The only case where version is present in composer.json is the binary distribution. Otherwise pickle will look for the version string in the extension header.
