### ISSUE TITLE
Incomplete json schema

### ISSUE THREAD

**Issue by pierrejoye** [FriendsOfPHP/pickle#112]
We should rely on vendor/composer/composer/res/composer-schema.json instead.

Also introduced a bad bug, stability is not actually a valid property. The stability is actually part of the version string (makes much more sense). See https://packagist.org/about

Stability issue: https://github.com/FriendsOfPHP/pickle/issues/113

**Comment by weltling** [comment]
Removed even appending stability to the version string. It's all should be (or be ommited for stable) in the version string. No need to dump or touch version strings we originally read in from sources or binary meta.
