### ISSUE TITLE
test fails

### ISSUE THREAD

**Issue by pierrejoye** [FriendsOfPHP/pickle#116]
> There is 1 error:
=> Pickle\tests\units\Package\PHP\Util\XML\Loader::testParse():
==> Error CATCHABLE FATAL ERROR in /home/pierre/project/pickle/pickle/tests/units/Package/PHP/Util/XML/Loader.php on unknown line, generated by file /home/pierre/project/pickle/pickle/src/Package/Util/Header/Version.php on line 16:
Argument 1 passed to Pickle\Package\Util\Header\Version::__construct() must be an instance of Pickle\Base\Interfaces\Package, instance of mock\Composer\Package\PackageInterface given, called in /home/pierre/project/pickle/pickle/src/Package/PHP/Util/XML/Loader.php on line 101 and defined
> There is 1 uncompleted method:
=> Pickle\tests\units\Package\PHP\Util\XML\Loader::testParse() with exit code 255:

**Comment by weltling** [comment]
This test should have been fixed earlier, but even not sure where. Another test was failing for me, in the same file.
