### ISSUE TITLE
Preparing next release

### ISSUE THREAD

**Issue by Hywan** [FriendsOfPHP/pickle#119]
Hello :-),

I would be glad to release a new version but what is the current state? Do we need to wait on some bug to be fixed before the release?

**Comment by pkruithof** [comment]
ping :)

Since release 0.4.0 there have been 221 commits. I'm currently looking at (finally) replacing pear/pecl for pickle, but I'm not sure if I should use dev-master here (is it stable enough?), or use an old version.

**Comment by pierrejoye** [comment]
WIll be done tonight :)

(what a long time ;)

**Comment by Hywan** [comment]
:-p
