### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by tmatsuo** [FriendsOfPHP/pickle#125]
I'm considering to use this tool, but it's not clear to me and it blocks me from using it.

Thanks :)

**Comment by pierrejoye** [comment]
New BSD.

Totally forgot to add it :)

**Comment by tmatsuo** [comment]
No worries. I'd appreciate it if you could add an explicit LICENSE file and ideally license headers in PHP files. Thanks!

**Comment by pierrejoye** [comment]
Yes, I will asap :)
