### ISSUE TITLE
PHP7 compatibility

### ISSUE THREAD

**Issue by teohhanhui** [FriendsOfPHP/pickle#129]
> Fatal error: Cannot use 'String' as class name as it is reserved in phar:///usr/local/bin/pickle/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/String.php on line 18

**Comment by Hywan** [comment]
Thanks :-).

**Comment by jubianchi** [comment]
Can we close this issue since json-schema has been bumped ?

**Comment by Hywan** [comment]
Yup.

**Comment by marcioAlmada** [comment]
The latest phar release still throws this error.
