### ISSUE TITLE
feature request: install would adopt better version requirement syntax

### ISSUE THREAD

**Issue by shouze** [FriendsOfPHP/pickle#133]
For example both `v4.*` & `5.*` of [apcu](http://pecl.php.net/package/APCu) are stable... but of course one is for `php >= 7.0` only.... so for example if you use php 5.6... should be cool to support such a syntax:

``` bash
pickle install `apcu-4.*`
```

More generally would the composer version requirement code should be used to do that?

**Comment by pierrejoye** [comment]
This is defined by the composer.json of the requested extensions. Adding it
with the version expression can and will conflict with the version of the
extension itself.

I am not sure if composer allows something to be passed in the cmd line to
tell to grab a version  requiring a minimum php version. @seldaek?

**Comment by shouze** [comment]
@pierrejoye ok I was using an old (0.2.0) release so I think I'm up to date now... I didn't understood about this composer.json file you were talking about. I've patched https://github.com/krakjoe/apcu-bc/pull/6 so I've also opened an issue to add a composer.json file to this extension too https://github.com/krakjoe/apcu-bc/issues/7 is that right?

**Comment by Seldaek** [comment]
As of a month or two ago, composer's VersionSelector class allows you to provide a current php version that the requirement must support to be automatically selected. So this would help here, but anyway to help you more I'd need to see the code and exaclty what you are doing to guess the version when none is provided.

**Comment by shouze** [comment]
@Seldaek @pierrejoye ok so I'm not so wrong with that PR? https://github.com/krakjoe/apcu-bc/pull/8/files

**Comment by pierrejoye** [comment]
@shouze looks good :)

You do not need to put the version as it will grab from the tag and the header file. It will also avoid multiple editing or to forget to change one place and get an error (versions mismatch)

**Comment by pierrejoye** [comment]
Reopen if you still experience this issue
