### ISSUE TITLE
Invalid version string

### ISSUE THREAD

**Issue by cmodijk** [FriendsOfPHP/pickle#134]
I'm trying to install imagick using pickle but i'm getting the following error

```
Invalid version string "3.4.0RC3-beta" 
```

Command used to install `./bin/pickle install imagick` 

The version i'm using is the latest checkout 5ad1daf0396174d96d616b8b0b05c0979b85fd7d

**Comment by Hywan** [comment]
Thanks for the report! We will look at this after the parties ;-).

**Comment by pierrejoye** [comment]
I am not sure howwe have to deal with that as it is clearly not semver. Without implemeting a version cleanup if composer's version parser failed, it may ignore these releases.

I can imagine (thinking loud) two solutions:

* we ignore these tags or versions
* we parse on error and try again passing a correct version to composer

Also I am not  sure the parsing and second try works as composer will called again on install. Maybe cleaning up while generating the package.json may help.

**Comment by Hywan** [comment]
@cmodijk Did you try to install imagick in the past with Pickle?

**Comment by cmodijk** [comment]
@pierrejoye No it's not an valid semver but i'm trying to install a stable version and not this specific version. I personally think you could ignore these kind of tags and versions let people define valid semver versins if they want to be able to be installed using Pickle. 

@Hywan No i have not tried to install imagick before normally i use pecl to do this but i'm trying to move al of our pecl install's to Pickle.

**Comment by Seldaek** [comment]
IMO ignoring those invalid versions would be a valid way to handle it, that's what we do in composer when a tag can't be normalized we ignore it. People have to stop doing such nonsense as a RC-beta really :)

**Comment by pierrejoye** [comment]
Ok, closing this issue as it is something that should be fixed in the respective package.

**Comment by umpirsky** [comment]
Same just happened:

```
$ ./bin/pickle install amqp
  - Installing amqp (latest-stable)
    Downloading: 100%         

  [UnexpectedValueException]                 
  Invalid version string "1.7.0alpha2-beta"  
```

**Comment by cmodijk** [comment]
@pierrejoye I think pickle should still ignore these versions and not index them like composer is doing

**Comment by umpirsky** [comment]
Is there any way to force which version I want to install with pickle?

**Comment by jubianchi** [comment]
@umpirsky `pickle install <extension>@<version>` should work

**Comment by umpirsky** [comment]
@jubianchi Worked, thanks! :+1:

**Comment by pierrejoye** [comment]
We should document this trick so users can install old tags or from zip if
desired

**Comment by hhoechtl** [comment]
Unfortunately the naming convention of PECL packages seems to be always `<version-core><pre-release>-<stability>`. E.g. also `5.3.2RC2-beta` for `redis` currently
