### ISSUE TITLE
Support package.xml versions < 2.0

### ISSUE THREAD

**Issue by mbrodala** [FriendsOfPHP/pickle#145]
It seems like a lot of PHP extensions do not provide a `package.xml` in version 2.0, [e.g. bz2](https://github.com/php/php-src/blob/a006363aeaf90fe00599ab76d06c25dfe2a5feb2/ext/bz2/package.xml) (see [live issue](https://github.com/Shippable/support/issues/2846)).

This prevents installing all of these extensions via Pickle:

```
  [RuntimeException]                                               
  Unsupported package.xml version, 2.0 or later only is supported
```

Thus this is the current list of actually installable PHP extensions:
- [ ] [bcmath](https://github.com/php/php-src/blob/a006363aeaf90fe00599ab76d06c25dfe2a5feb2/ext/bcmath/package.xml)
- [ ] [bz2](https://github.com/php/php-src/blob/a006363aeaf90fe00599ab76d06c25dfe2a5feb2/ext/bz2/package.xml)
- [ ] [calendar](https://github.com/php/php-src/blob/a006363aeaf90fe00599ab76d06c25dfe2a5feb2/ext/calendar/package.xml)
- [ ] [com_dotnet](https://github.com/php/php-src/blob/a006363aeaf90fe00599ab76d06c25dfe2a5feb2/ext/com_dotnet/package.xml)
- [ ] [ctype](https://github.com/php/php-src/blob/a006363aeaf90fe00599ab76d06c25dfe2a5feb2/ext/ctype/package.xml)
- [ ] [curl](https://github.com/php/php-src/blob/a006363aeaf90fe00599ab76d06c25dfe2a5feb2/ext/curl/package.xml)
- [x] [enchant](https://github.com/php/php-src/blob/a006363aeaf90fe00599ab76d06c25dfe2a5feb2/ext/enchant/package.xml)
- [ ] [exif](https://github.com/php/php-src/blob/a006363aeaf90fe00599ab76d06c25dfe2a5feb2/ext/exif/package.xml)
- [ ] [fileinfo](https://github.com/php/php-src/blob/a006363aeaf90fe00599ab76d06c25dfe2a5feb2/ext/fileinfo/package.xml)
- [ ] [ftp](https://github.com/php/php-src/blob/a006363aeaf90fe00599ab76d06c25dfe2a5feb2/ext/ftp/package.xml)
- [ ] [hash](https://github.com/php/php-src/blob/a006363aeaf90fe00599ab76d06c25dfe2a5feb2/ext/hash/package.xml)
- [ ] [mysqli](https://github.com/php/php-src/blob/a006363aeaf90fe00599ab76d06c25dfe2a5feb2/ext/mysqli/package.xml)
- [x] [oci8](https://github.com/php/php-src/blob/a006363aeaf90fe00599ab76d06c25dfe2a5feb2/ext/oci8/package.xml)
- [ ] [pcntl](https://github.com/php/php-src/blob/a006363aeaf90fe00599ab76d06c25dfe2a5feb2/ext/pcntl/package.xml)
- [x] [phar](https://github.com/php/php-src/blob/a006363aeaf90fe00599ab76d06c25dfe2a5feb2/ext/phar/package.xml)
- [ ] [posix](https://github.com/php/php-src/blob/a006363aeaf90fe00599ab76d06c25dfe2a5feb2/ext/posix/package.xml)
- [ ] [session](https://github.com/php/php-src/blob/a006363aeaf90fe00599ab76d06c25dfe2a5feb2/ext/session/package.xml)
- [ ] [shmop](https://github.com/php/php-src/blob/a006363aeaf90fe00599ab76d06c25dfe2a5feb2/ext/shmop/package.xml)
- [ ] [soap](https://github.com/php/php-src/blob/a006363aeaf90fe00599ab76d06c25dfe2a5feb2/ext/soap/package.xml)
- [ ] [sockets](https://github.com/php/php-src/blob/a006363aeaf90fe00599ab76d06c25dfe2a5feb2/ext/sockets/package.xml)
- [ ] [spl](https://github.com/php/php-src/blob/a006363aeaf90fe00599ab76d06c25dfe2a5feb2/ext/spl/package.xml)
- [ ] [sysvmsg](https://github.com/php/php-src/blob/a006363aeaf90fe00599ab76d06c25dfe2a5feb2/ext/sysvmsg/package.xml)
- [ ] [sysvsem](https://github.com/php/php-src/blob/a006363aeaf90fe00599ab76d06c25dfe2a5feb2/ext/sysvsem/package.xml)
- [ ] [sysvshm](https://github.com/php/php-src/blob/a006363aeaf90fe00599ab76d06c25dfe2a5feb2/ext/sysvshm/package.xml)
- [ ] [tidy](https://github.com/php/php-src/blob/a006363aeaf90fe00599ab76d06c25dfe2a5feb2/ext/tidy/package.xml)
- [ ] [tokenizer](https://github.com/php/php-src/blob/a006363aeaf90fe00599ab76d06c25dfe2a5feb2/ext/tokenizer/package.xml)
- [ ] [wddx](https://github.com/php/php-src/blob/a006363aeaf90fe00599ab76d06c25dfe2a5feb2/ext/wddx/package.xml)
- [ ] [xml](https://github.com/php/php-src/blob/a006363aeaf90fe00599ab76d06c25dfe2a5feb2/ext/xml/package.xml)
- [ ] [xmlreader](https://github.com/php/php-src/blob/a006363aeaf90fe00599ab76d06c25dfe2a5feb2/ext/xmlreader/package.xml)
- [ ] [xmlwriter](https://github.com/php/php-src/blob/a006363aeaf90fe00599ab76d06c25dfe2a5feb2/ext/xmlwriter/package.xml)

This vastly limits the usage of Pickle from my POV, thus `package.xml` before version 2.0 should also be supported.

Or am I misunderstanding something?

**Comment by weltling** [comment]
Thanks for doing the check. The extensions you list are in the core, they're usually shipped by a distro. As the core extensions are not provided separately in any repositories, they won't be able to be fetched. The PECL command won't fetch them, too. Well, they could be fetched if moved out from the core, but in that case you'll often get some outdated version, except it's a maintained fork. The only way pickle to provide core extensions would be to implement support for every package systems, this is probably not what pickle is intended for. 

Thanks.

**Comment by mbrodala** [comment]
@weltling So, that means I should check somewhere else instead? How is the exact flow Pickle performs, e.g. when installing "bz2" on an Ubuntu distro? (Or "intl" which seems to work fine.)

**Comment by pierrejoye** [comment]
Some like zip are in pecl too and have separate releases.

**Comment by mbrodala** [comment]
I see, that's why [intl](https://pecl.php.net/package/intl) works.

**Comment by weltling** [comment]
Exactly, every distro decides how to deliver the core extensions. Some are available with just a basic PHP package, some are separate packages. If an extension is in PECL, it might be actively maintained with all the bug and security fixes, fe like ext/zip. In other cases, you might get quite an outdated package.

So with the core extensions, relying on the distro packages makes more sense except you know exactly about a particular ext. On the other side, pickle gives you flexibility to install non core extensions from github, etc. But neither Pickle nor PECL would install extensions from the PHP core. Pickle focuses on better Composer integration and on the installation simplification of the non core exts, including those not available in PECL, fe from GitHub.

Thanks.

**Comment by mbrodala** [comment]
OK, so if an extension like `bz2` is available neither via PECL nor by distribution package, the latter should be fixed I guess. I'll try that and report back.

**Comment by pierrejoye** [comment]
You can pass the repository too.

**Comment by mbrodala** [comment]
@pierrejoye How would that work with [phpenv](https://github.com/phpenv/phpenv)? That's what various environments like Shippable CI use to provide multiple PHP versions.

**Comment by pierrejoye** [comment]
@mbrodala what do you mean? You can run pickle with each php and it should install exts for each of them

**Comment by mbrodala** [comment]
@pierrejoye Could you give me an example? Currently it [doesn't work](https://github.com/Shippable/support/issues/2846) for me.

**Comment by pierrejoye** [comment]
That would be too much for a one time action, git or peck convert can be used :)

**Comment by renepardon** [comment]
It's not possible to install "tidy" extension on MAMP like this:

```bash
pickle install --php=/Applications/MAMP/bin/php/php8.0.8/bin/php --ini=/Library/Application\ Support/appsolute/MAMP\ PRO/conf/php8.0.8.ini tidy
```

I receive exactyl this error: 

```bash
In Loader.php line 165:

  Unsupported package.xml version, 2.0 or later only is supported
```

**Comment by pierrejoye** [comment]
Please report there. It is relatively easy to convert package.xml to 2.0
and do a release then.
