### ISSUE TITLE
New tag?

### ISSUE THREAD

**Issue by alexbowers** [FriendsOfPHP/pickle#147]
There has been 225 commits since `0.4.0` got tagged, is there anything in particular holding up a `0.5.0` release?

**Comment by Hywan** [comment]
We have some work we would like to pass on the 0.5.0, for instance green tests.

**Comment by alexbowers** [comment]
Is there a list of things of varying difficulty that I could contribute to?

**Comment by petk** [comment]
Bumping this (sorry in advance). It would be useful to have more tags no matter the stability of current master. I think it is more stable and working better than the `v0.4.0`. Yes/no?
