### ISSUE TITLE
Version::findHeaders() exception for missing version macro is never used

### ISSUE THREAD

**Issue by jmikola** [FriendsOfPHP/pickle#151]
While looking into https://github.com/mongodb/mongo-php-driver/issues/562, I trace the "Couldn't parse the version defined in the PHP_MONGODB_VERSION macro" error message down to [`Version::getVersionFromHeader()`](https://github.com/FriendsOfPHP/pickle/blob/b4ff87802c8c7823f3fb08b4f14dfb0b5492e025/src/Package/Util/Header/Version.php#L90). In the same file, I found [`Version::findHeaders()`](https://github.com/FriendsOfPHP/pickle/blob/b4ff87802c8c7823f3fb08b4f14dfb0b5492e025/src/Package/Util/Header/Version.php#L58), which includes a related error message:

> No macro named PHP_MONGODB_VERSION was found in the headers. This macro is recommended to be defined with the current extension version

Unfortunately, `Version::findHeaders()` does not appear to be called anywhere. Is it dead code, or is there some extending class that relies on this protected method? Its exception message seems more helpful in the event that an extension is missing the macro entirely, rather than containing a value that cannot be properly parsed.

**Comment by pierrejoye** [comment]
Version::fileHasVersionMacro is used, findHeaders was the 1st version of it, I think it can be removed.

**Comment by pierrejoye** [comment]
It should be fixed now, we search through all directories recursively.

Reopen if you still have the issue after the next release (or using master)
