### ISSUE TITLE
php-src no phpize.js

### ISSUE THREAD

**Issue by yangweijie** [FriendsOfPHP/pickle#156]
![image](https://user-images.githubusercontent.com/1614114/41503698-01c73606-720d-11e8-8152-7e8f9053ee1c.png)
i found phpize.bat. But don't know how generate phpize.js.There is no build/script Directory.

**Comment by pierrejoye** [comment]
You need to have the php-SDK installed and either in your path or using argument.

**Comment by pierrejoye** [comment]
Phpize then can generate it.
