### ISSUE TITLE
Issue when path to php executable contains space(s) 

### ISSUE THREAD

**Issue by jacklul** [FriendsOfPHP/pickle#158]
Windows. 
If the path contains space(s) the script cannot locate PHP correctly, even if the path is given in quotes via `--php` argument.

Everything works fine after putting quotes around `$this->phpCli` in appropriate places (`Engine/PHP.php`).

**Comment by pierrejoye** [comment]
fixed in master.

0.6.0 will use symfony/process to avoid this to come back, and enforce no direct exec&co usage.

thanks you :)
