### ISSUE TITLE
PHP 7.0+ Compatibility

### ISSUE THREAD

**Issue by SerafimArts** [FriendsOfPHP/pickle#159]
Pickle version 0.4.0 (last stable: https://github.com/FriendsOfPHP/pickle/releases)

This is a repetition of this https://github.com/FriendsOfPHP/pickle/issues/129 error that has not yet been repaired.

Error:
```
PHP Fatal error:  Cannot use 'String' as class name as it is reserved in phar:///home/travis/build/railt/railt/pickle.phar/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/String.php on line 18
```

Is it planned to support pickle? Because I can't use PECL because it is not compatible with php 8.0-dev :D

**Comment by pierrejoye** [comment]
We should report this bug to Json-Shema :)

**Comment by staabm** [comment]
I guess we need to update json schema. Pickle depends on ^1.5 but the latest version is 5.x

https://github.com/justinrainbow/json-schema/releases

I guess somewhere in between php7 compat was added

**Comment by SerafimArts** [comment]
> We should report this bug to Json-Shema :)

Nope =) As @staabm  correctly said, you just need to update it

**Comment by pierrejoye** [comment]
even better :))

**Comment by pierrejoye** [comment]
This is fixed, in Atoum too :)
