### ISSUE TITLE
[Bug]: Ini not updated on Linux / MacOS

### ISSUE THREAD

**Issue by ruudboon** [FriendsOfPHP/pickle#166]
Installed packages aren't enabled in the php.ini on Linux and MacOS.
Looks like this only happening under windows and HHVM.

**Comment by Hywan** [comment]
I think it is on-purpose. If that happens only for HHVM on Windows, it's probably not a standard feature.

**Comment by ruudboon** [comment]
Can we choose a standard for this? Enable it for all platforms or disable it by default and have something like a property `--add-extension-to-ini`?

Maybe we can have a look how Pecl is currently solving this so it will be easy for users to switch to to Pickle.

**Comment by Hywan** [comment]
I think it's better to not touch the `php.ini` file automatically. It's out the boundaries of this tool.

**Comment by morrisonlevi** [comment]
In my opinion, it is fair game to add new files to the ini scan directory, but modifying files should be a no-no.

**Comment by pierrejoye** [comment]
I think we could add to php.ini, or add an output for the user to add the line. 

It is easy to add the line, it is not easy to remove any other that could be the same extensions or different extension version.

**Comment by pierrejoye** [comment]
As of PHP itself (not HHVM as the support for HHVM has been droped), it works as expected.
