### ISSUE TITLE
Unable to install memcached and uuid

### ISSUE THREAD

**Issue by salarmehr-cbs** [FriendsOfPHP/pickle#174]
It seems that Pickle does not try to compile an extension when there is no DDL of Windows

```

C:\server\pickle>php bin/pickle install memcached
+---------------+--------------------------+
| php Path      | C:^\server^\php^\php.exe |
| php Version   | 7.4.5                    |
| Compiler      | vc15                     |
| Architecture  | x64                      |
| Thread safety | no                       |
| Extension dir | C:\server\php\ext        |
| php.ini       | C:\server\php\php.ini    |
+---------------+--------------------------+


  [Exception]
  Binary for <memcached-3.1.5> cannot be found
```

or 

```
C:\server\pickle>php bin/pickle install uuid
+---------------+--------------------------+
| php Path      | C:^\server^\php^\php.exe |
| php Version   | 7.4.5                    |
| Compiler      | vc15                     |
| Architecture  | x64                      |
| Thread safety | no                       |
| Extension dir | C:\server\php\ext        |
| php.ini       | C:\server\php\php.ini    |
+---------------+--------------------------+


  [Exception]
  Binary for <uuid-1.1.0> cannot be found


install [--no-convert] [--defaults] [--source] [--with-configure-options WITH-CONFIGURE-OPTIONS] [--save-logs SAVE-LOGS] [--dry-run] [--php PHP] [--ini INI] [--tmp-dir TMP-DIR] [--binary] [--] [<path>]
```
I managed to get membcahced from https://github.com/lifenglsf/php_memcached_dll but could not find a pre-complided windows version for uuid. 

I was hoping to be able to use Pickle to install those packages on Windows.

**Comment by salarmehr-cbs** [comment]
Actually, for UUID it may not be possible to compile it for Windows.

**Comment by pierrejoye** [comment]
pecl's UUID does not have config file to build on windows. Apparently the library either.

Maybe you can report to the UUID extension project to do something like:

https://github.com/postwait/node-libuuid/issues/5

You can tell them to ping me or CMB if Ben needs help to implement or test :)

**Comment by pierrejoye** [comment]
We have built a windows build infrastructure for windows binaries, php and pecl sources (or on demand for github).

Memcached, for some reasons the https://pecl.php.net/package/memcached does not have DLLs. I would suggest them to contact the PHP windows team (Weltling or CMB ;) ) to sort it out. It used to have it.

Once the DLL is available in pecl.php.net, pickle can fetch it automatically.

We may add an option to fetch the DLL from github if the developers of a given extension provide them but so far this is the only I know doing so, and only in github.

**Comment by pierrejoye** [comment]
@cmb69  Maybe you can see with the memcached maintainer? UUID is a bit more work :)

**Comment by pierrejoye** [comment]
Also see https://github.com/FriendsOfPHP/pickle/issues/176, which basically kills pickle windows support with latest php 7.4 :-( The standard I defined back then are gone in php core. Let see how we can sort it out.

**Comment by cmb69** [comment]
I don't think that an automatic fallback to self-compilation if there is no prebuilt DLL available is in place. You can manually force self-compilation by passing the `--source` option (which should work at least for extensions without special library dependencies).

It seems to me that PECL/memcached DLLs have never been built before, and given that [libmemcached is abandoned](https://launchpad.net/libmemcached/+download) and also given that [PECL/memcache is maintained](https://pecl.php.net/package/memcached), it might be better to keep it that way.

For PECL/UUID, the situation isn't that different; apparently, [libuuid is abandoned](https://sourceforge.net/projects/libuuid/) as well. I have doubts that we have the bandwidth to cater to potential necessary security fixes in these libraries.

**Comment by pierrejoye** [comment]
@cmb is fully correct. I I mixed up both in my comment.

memcahe does not rely on any lib while memcached relies on libmemcached,
which was at the time the de facto standard. At least it has the merit to
make it clear now  :)

**Comment by cmb69** [comment]
I just noticed that I was wrong about libuuid. The PECL package description says "A wrapper around libuuid from the ext2utils project.", and [ext2utils are well maintained](https://git.kernel.org/pub/scm/fs/ext2/e2fsprogs.git/). I'll have a look at it.

**Comment by cmb69** [comment]
I seriously doubt that it makes sense to build libuuid for Windows in its current state. Besides that it needs some minor patches to even compile (e.g. there is no `getuid()` on Windows), the functionality is severely restricted on Windows: [`get_node_id()` always returns 0](https://git.kernel.org/pub/scm/fs/ext2/e2fsprogs.git/tree/lib/uuid/gen_uuid.c#n220), `uuid_generate()` always calls `uuid_generate_time()` and `get_random_bytes()` only uses a PRNG, so the generated numbers may not comply with CSPRNG requirements.

If you feel strongly that PECL/uuid should be supported on Windows, please file a feature request at https://bugs.php.net. Thanks.

**Comment by pierrejoye** [comment]
Issue here solved per se from a pickle point of view.

Thanks @salarmehr-cbs and @cmb69 for your time and support!
