### ISSUE TITLE
Invalid version string

### ISSUE THREAD

**Issue by hhoechtl** [FriendsOfPHP/pickle#188]
I'm trying to install the package `yaml` on PHP 8.0 beta1 but I get:
```
Invalid version string "2.2.0b1-beta"  
```

**Comment by josefsabl** [comment]
I am having similar issue:

```RUN pickle install yaml@2.2.0b1```

ends with:

```
In Pickle.php line 65:

  http error while loading informatio for yaml@2.2.0b1: unknown error
```

**Comment by pierrejoye** [comment]
See https://github.com/FriendsOfPHP/pickle/issues/165

In short, we should report to them to use semver versions.

**Comment by mcfedr** [comment]
Would be useful to allow pickle to ignore this version in someway - had a similar issue, where i want to install xdebug dev version from source,  `pickle install git://github.com/xdebug/xdebug.git`, and you get the error, `Version mismatch - '3.0.0-dev' != '2.8.0beta1' in source vs. XML`.
