### ISSUE TITLE
Make ext-zip optional

### ISSUE THREAD

**Issue by derrabus** [FriendsOfPHP/pickle#195]
When running `pickle` in an enviroment without `ext-zip`, it fails early. This is for instance the case with the php binary that is bundled with macOS.

```
Fatal error: Uncaught Exception: Extension 'zip' required but not loaded, full required list: zlib, mbstring, simplexml, json, dom, openssl, phar, zip
```

To me, this seems like an unnecessary hard requirement. I recognize that on Windows, php extensions come precompiled and are distributed as ZIP files. But for other platforms, extensions are usually distributed as source tarballs.

Would it be possible to loosen that requirement a bit?

**Comment by juliangut** [comment]
Fully agree with @derrabus

**Comment by pierrejoye** [comment]
would be possible however I see many where the code is downloaded (using
composer) from git, as zip.

I won't have the time to do it, however if you have time feel free to do
it. It needs quite a few places to be changed, and it also may need
composer updates afair.
