### ISSUE TITLE
Will there be another release before PHP8 comes out?

### ISSUE THREAD

**Issue by tobybellwood** [FriendsOfPHP/pickle#199]
Hi - Thanks so much for the recent activity on this, I've been using Pickle to install our PECL extensions for all our PHP8 testing to date - it's working well, and the fixes to master to allow a version override work brilliantly, especially as only 2/5 of our extensions are PHP8 ready in the stable release.

I've been downloading a .phar of master from my own repo to date - and will probably create our own upstream image to allow us to do https://github.com/FriendsOfPHP/pickle/issues/194 - but it'd be great to get the latest master into a release with a downloadable .phar file.

Is this something that's on the cards?

**Comment by mleczakm** [comment]
Release please #189 because without this fix many extensions can't be installed and building phar from source inside dockerfile is a bit complicated.

**Comment by mleczakm** [comment]
PING :)

**Comment by Ilyes512** [comment]
Is there any schedule or plan?

**Comment by pierrejoye** [comment]
should, but I am very busy right now with my company.

I will have time during Xmas break.

PRs welcome tho', if tests pass i will merge and release  :)

**Comment by mlocati** [comment]
We now have a new version (0.7.0)
