### ISSUE TITLE
Pickle try to load wrong extension version

### ISSUE THREAD

**Issue by tburschka** [FriendsOfPHP/pickle#200]
It seems, that pickle doesn't respect the option downloading the latest-stable version, in case of mongodb it's 1.8.2 and not 1.9.0RC1. (I'm using the latest pickle.phar)

    pickle install mongodb
    Installing mongodb (latest-stable): Downloading (100%)
    In VersionParser.php line 176:
    Invalid version string "1.9.0RC1-beta"

**Comment by mlocati** [comment]
This issue should have been fixed by #201
