### ISSUE TITLE
Incorrect version suffix for non-stable releases

### ISSUE THREAD

**Issue by duncan3dc** [FriendsOfPHP/pickle#202]
I see a change was made in baa3a37da0ee713eaa82fba7598c0f621ff9a7b6 which respected the version string from the extension.
However it looks like this was reverted in f2548dc8f62b78ac337bfa208746c57c362efbed which is now causing issues like https://github.com/microsoft/msphpsql/issues/1210 (`Invalid version string "5.9.0beta2-beta"`)

Does anybody know why f2548dc8f62b78ac337bfa208746c57c362efbed was committed?

**Comment by mlocati** [comment]
This issue should have been fixed by #201
