### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by mlocati** [FriendsOfPHP/pickle#204]
I'd need to know if I should wait for a new pickle version in the near future, or if I have to look for alternatives to pickle...

**Comment by Hywan** [comment]
I'm no longer co-maintaining the project. Maybe @pierrejoye or @jubianchi could provide further details?

**Comment by pierrejoye** [comment]
I do, can see the commits, lacking time to do the changes for php8 lately.
Kind of over busy, contribution welcome!

**Comment by mlocati** [comment]
@pierrejoye well, I tried to contribute, but I received no feedback in more that a month...

For example, [here](https://github.com/FriendsOfPHP/pickle/issues/191#issuecomment-736561016) I suggested a way that would let you publish a new version by simply pushing a new tag...

**Comment by pierrejoye** [comment]
PR Merged. I will try a release over the weekend! :)

**Comment by mlocati** [comment]
> PR Merged. I will try a release over the weekend! :)

Great! It should be as easy as:
1. pushing a new version-like tag to the github repository
2. wait until [the GitHub Action](https://github.com/FriendsOfPHP/pickle/actions) completes
3. go to the [releases](https://github.com/FriendsOfPHP/pickle/releases) page
4. review the draft release that has been created automatically
5. publish that draft release
