### ISSUE TITLE
How to pass configuration options?

### ISSUE THREAD

**Issue by speller** [FriendsOfPHP/pickle#241]
It says that pickle is intended for ease of extension management. But I'm stuck with passing configuration options while installing the `redis` extension. It asks for many options during the installation but I want to pass their values in the CLI. How to do that? I can't find their names and how to pass them, no documentation.

I understood that these are the default:

```
Configure options
+--------+---------------------------------------+---------+
| Type   | Description                           | Default |
+--------+---------------------------------------+---------+
| with   | use system liblzf                     |         |
| with   | use system libsztd                    |         |
| with   | use system liblz4                     |         |
| enable | whether to enable redis support       | no      |
| enable | whether to enable sessions            | yes     |
| enable | whether to enable json serializer     | yes     |
|        | support                               |         |
| enable | whether to enable igbinary serializer | no      |
|        | support                               |         |
| enable | whether to enable msgpack serializer  | no      |
|        | support                               |         |
| enable | whether to enable lzf compression     | no      |
| enable | whether to enable Zstd compression    | no      |
| enable | whether to enable lz4 compression     | no      |
+--------+---------------------------------------+---------+
```
And how to override them?

**Comment by speller** [comment]
When I install redis with default values, it doesn't work: 

```
$pickle install redis --defaults -n
...(all succeeds)
$ php -i | grep redis
#18 0.353 This program is free software; you can redistribute it and/or modify
```

How to use pickle at all??? I just want the extension installed and loaded but can't do that with all defaults.

**Comment by mlocati** [comment]
You can use the `--with-configure-options` option.

Write a file containing the options defined in the `package.xml` file provided by the package ([here's the one for redis 5.3.4](https://github.com/phpredis/phpredis/blob/5.3.4/package.xml#L129-L133), or use my https://mlocati.github.io/pecl-info tool).

For example, for [redis 5.1.0 and later](https://mlocati.github.io/pecl-info/#redis), you can use a file containing these lines:

```
--enable-redis-igbinary=yes
--enable-redis-lzf=no
--enable-redis-zstd=no
```

If you save this file as `options.txt`, you can call picke with `--with-configure-options options.txt`.
