### ISSUE TITLE
Pickle picks RC instead of latest stable

### ISSUE THREAD

**Issue by ruudk** [FriendsOfPHP/pickle#247]
```
$ pickle install --defaults redis
  - Installing redis (latest-stable): Downloading (100%)
+-----------------------------------+----------+
| Package name                      | redis    |
| Package version (current release) | 5.3.5RC1 |
| Package status                    | RC       |
+-----------------------------------+----------
```

Why does it install RC version (tagged as beta on pecl) instead of the latest real stable?

**Comment by akalineskou** [comment]
I use `pickle install --defaults redis@5.3.6` so that it uses the version I want and periodically check https://mlocati.github.io/pecl-info/ for new versions (uncheck compat versions to view all)

That does not answer why it does that, but it's a fix

**Comment by michael-schaefer-eu** [comment]
@akalineskou that's not a fix , that's a workaround ;)

I have the same with xdebug - and it even says `installing latest-stable` :face_with_spiral_eyes: 

```
 > [php_with_development_tools 1/6] RUN /usr/local/bin/pickle.phar install --no-interaction xdebug:
#24 0.354   - Installing xdebug (latest-stable): Downloading (100%)         
#24 1.592 +-----------------------------------+-------------+
#24 1.592 | Package name                      | xdebug      |
#24 1.592 | Package version (current release) | 3.2.0alpha1 |
#24 1.592 | Package status                    | alpha       |
#24 1.592 +-----------------------------------+-------------+
```

EDIT: Nice while I was writing this, a fix has been proposed. That was fast :D

**Comment by b1rdex** [comment]
@michael-schaefer-eu check https://github.com/FriendsOfPHP/pickle/pull/259 for a fix

**Comment by b1rdex** [comment]
@ruudk any comment about why this is not planned?

**Comment by ruudk** [comment]
I don't care for this issue anymore.
