### ISSUE TITLE
Install version by GH branch

### ISSUE THREAD

**Issue by mvorisek** [FriendsOfPHP/pickle#254]
For development, I need other version than the tagged ones.

The doc does not mention this usecase - https://github.com/FriendsOfPHP/pickle#usage

This issue is a question. Does pickle support is, eg. does it know which GH repo to use and how to specify the wanted git branch as a version?

**Comment by fabiang** [comment]
You could checkout that branch with git into a folder and run `pickle install /tmp/checkedoutrepo`. The install commands also supports paths:

> Description:
  Install a php extension  
Usage:
  install [options] [--] [<path>]  
Arguments:
  path                                                 Path to the PECL extension root directory (default pwd), archive or extension name [default: "/"]
