### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by ruudk** [FriendsOfPHP/pickle#265]
Is this project still maintained? 

I noticed this [comment](https://github.com/FriendsOfPHP/pickle/issues/263#issuecomment-1363211277) from @mlocati:
> Yet another good reason to drop pickle and keep using pecl

Does this mean we should no longer use Pickle?

**Comment by mlocati** [comment]
I've contributed to this project because I needed pickle.
But now I've switched back to pecl, and I'm not going to spend my time on this project anymore.

This obviously doesn't prevent someone else from contributing to it.
