### ISSUE TITLE
[Insight] Code should not be duplicated

### ISSUE THREAD

**Issue by pborreli** [FriendsOfPHP/pickle#65]
**[in src/Console/Command/InstallerCommand.php, line 168](https://github.com/FriendsOfPHP/pickle/blob/master/src/Console/Command/InstallerCommand.php#L168)**

> The next 19 lines appear both in `src/Console/Command/InstallerCommand.php:168` and `src/Console/Command/ReleaseCommand.php:37`.

```php
            }

            $path = sys_get_temp_dir() . DIRECTORY_SEPARATOR . $package->getName();
        }

        $jsonLoader = new Package\JSON\Loader(new Package\Loader());
        $package = null;

        if (file_exists($path . DIRECTORY_SEPARATOR . 'pickle.json')) {
            $package = $jsonLoader->load($path . DIRECTORY_SEPARATOR . 'pickle.json');
        }
```

---

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/7e153d04-79be-47e6-b2ee-60cdc2665dd5/analyses/56)_

**Comment by weltling** [comment]
Thanks for the check. Seems it not relevant anymore, the relevant code slided into src\Package\*\Convey\Command\DefaultExecutor.php, whereby the HHVM is to the big part waiting for some better implementation.

Thanks.
