### ISSUE TITLE
pickle and pecl-web api

### ISSUE THREAD

**Issue by jakoch** [FriendsOfPHP/pickle#71]
Hey Pierre, Hey Julien,

i've tested pickle on Windows. It works like charm. :+1: 

I took a quick glance at "InstallerBinaryWindows.php". The file uses an scraping approach to determine if an extension exists and which versions it has. Why is scraping preferred over using service functionalities provided by the https://github.com/php/web-pecl repository? I think the PECL website could need some love to provide a better service layer especially for the windows extensions. Something like Packagist provides for Composer.

So please let me suggest some ideas for PICKLE using PECL-WEB.

2. **pickle info**
Currently the info command downloads the extension and uses the package.xml for getting infos. I'm in doubt if you implemented this intentionally, so i have to ask: do you want an 1:1 pickle to extension archive? I would prefer to fetch extension infos via an api. 
Simply ask http://pecl.php.net/package/$ext-name.json for the extension details or use cached infos.

3. **pickle list**
Currently displays the list of commands, which doesn't make sense, because there's already "h, help or ?".
My suggestion is, that it should fetch a platform specific extensions list via api,
in order to lists all available extensions for a platform. Currently there is no way of listing all available extensions, besides scraping the download folder. The intention here is to get a extension list with latest version download urls with only one request.

 - Extension Lists as JSON
   - including name, beauty name, latest version, download url, url to fetch detailed package infos:
    - http://pecl.php.net/windows/extensions.json
    - http://pecl.php.net/windows/releases.json
    - http://pecl.php.net/windows/snaps.json
    - http://pecl.php.net/linux/extensions.json
    - http://pecl.php.net/linux/releases.json 
  
 - Extension Details
    - including name, desc, author, versions, latest version, download url per version and dependencies
    - http://pecl.php.net/package/amqp.json
 
**PECL web - housekeeping**

It's pretty obvious that most of the stuff living there is XML and not even used by the PHP core devs themself. If new tools, like Pickle are not utilizing this, then simply drop all that. Why not clean the house and remove unused things.

For instance, things like
- http://pecl.php.net/json.php?package=apc 
- http://pecl.php.net/rest/p/packages.xml
- http://pecl.php.net/rest/p/

The REST based Extension Listings doesn't differ between Linux and Windows extensions. Example: the "printer" extension exists on Linux, but only in "snaps" on Windows and not in "releases".

I imagine a very lean and clean JSON based API, without the need to scrape things.
Also the number of requests to the service API might be lowered by downloading the JSON data to the installing client or bundling the JSON files inside the PHAR.
     
Most of this seems unrelated to Pickle, but i think pecl-web could be for pickle, what "packagist is for composer. I hope that some of the ideas presented here make sense and are worth further discussion. Looking forward hearing from you.

Regards, Jens

**Comment by pierrejoye** [comment]
Little update:

We won't touch or update pecl.php.net to add the info to make pickle more efficient but create an independent packagist-like application to host the meta for PHP extensions.

Pickle already  works well using pecl.php.net and will continue to do so. But we do not see much points to actually deal with pecl.php.net directly, even less as pickle targets more than only php.net's php.

I hope it makes sense :)

**Comment by jakoch** [comment]
Thank you for pointing this out, Pierre.
This decision leads away from consolidation and cleanup of pecl.php.net.
So i'm no fan of this decision, but it's an interesting move away from php.net. :)

Why was this decision made? 

--- tl;tr --- cut here --- 

- It appears to me that nowadays new "PHP.net" sub-projects are created, which tend to avoid the official infrastructure, like the GoPHP7 extensions project and now the pickle packagist like-app.

- I don't see the need for an independent new application for the meta-data of PHP extensions.
For official PHP extensions PECL is the main site, why not deal with it directly.
Providers of non-php.net PHP extensions might provide their own API endpoint.
Their extensions, their meta-data, right?
That means for pickle: fetching extension data from multiple API endpoints is no problem.

- Secondly, why something independent new, when Packagist is out there, which could be extended.

- The flip-side of this decision is that pecl.php.net is only needed as a download source.
There's no need to maintain a PECL front-end anymore, if pickle-packagist has more data and provides a decent front-end it will become the central source for manual extension lookups.

Just my 2 cents regarding this matter.

Regards, Jens

**Comment by pierrejoye** [comment]
Not sure to understand all your points but here is an attempt to clarify the whole thing:

Most if not all meta data are available in the extension codes.

Packagist like model will be a single entry point for all extensions, no matter where and how an extension is maintained.

Pecl.php.net won't be needed anymore, not even to download sources or binaries.

I won't ask to shut pecl.php.net down or not. I simply do not care enough anymore. Too much pain to get what is required in place in php.net lately. As one of the creator of pecl/pear, having to beg for every single thing is annoying at best, killing all my good will to spend a single second on that at worst.

**Comment by jakoch** [comment]
The last few sentences make me feel a bit sad, especially when hearing them from a core contributor. But the situation can't be that worse, because i've seen you doing some cleanup commits over at pecl-web and the composer integration. Thumbs up!
