### ISSUE TITLE
Need a logo

### ISSUE THREAD

**Issue by Hywan** [FriendsOfPHP/pickle#89]
We need a logo :-). Any idea?

**Comment by Hywan** [comment]
@jubianchi Any news for the logo?

**Comment by Hywan** [comment]
@jubianchi Sorry to ping you again :-(.

**Comment by tarekdj** [comment]
Result of a developer playing with Adobe Illustrator :smile: 
![logo](https://cloud.githubusercontent.com/assets/540268/7025021/3b68324a-dd30-11e4-9f11-4bfc0f5fde26.jpg)

**Comment by pborreli** [comment]
not bad :+1:

**Comment by pierrejoye** [comment]
Like it :)

**Comment by tarekdj** [comment]
Thx guys! 
 I think it's better with less letters height

![logo](https://cloud.githubusercontent.com/assets/540268/7025746/26426746-dd35-11e4-8373-393c5a558f70.jpg)

**Comment by jubianchi** [comment]
<3 :+1:

**Comment by Hywan** [comment]
:+1:

Need an SVG export.

**Comment by willdurand** [comment]
:+1:

**Comment by tarekdj** [comment]
Work hosted on github: https://github.com/tarekdj/Pickle-Logo

**Comment by Hywan** [comment]
If everyone is agree, I will merge the logo on the repository.

**Comment by pierrejoye** [comment]
I have to say go ahead :)

**Comment by tarekdj** [comment]
:+1:

**Comment by Hywan** [comment]
Twitter's logo updated: https://twitter.com/Pickle_PHP.

**Comment by j0k3r** [comment]
Simple, efficient, nice :+1:

**Comment by jubianchi** [comment]
@Hywan what about just using the pickle as the logo on Twitter?

The full logo (pickle + text)  seems too small on the timeline.

**Comment by Hywan** [comment]
@jubianchi Just a pickle is not really in favor of the project, isn't it :-p?

**Comment by jubianchi** [comment]
@Hywan fair point :)
